implementing baseline code for socker.io
Code-the-Dream-School/cc-prac-team2-back pull request #9
Opened 2023-06-06 00:12 UTC by mdmontes

2023-06-06 21:35 UTC, Abdulaiman approved these changes
Great work! The changes in this pull request look good to me. I've reviewed the code and it seems to be in line with our project's standards.

2023-06-08 12:41 UTC, royemosby requested changes
Requesting minor change and had one question about imports

2023-06-08 12:41 UTC, royemosby commented on src/server.ts
> +import { Socket } from "socket.io";
What are these two different types of import statements doing?

2023-06-08 22:10 UTC, mdmontes commented on src/server.ts
> +import { Socket } from "socket.io";
Hey Roy,

The Lower case "socket" is the socket object that we are using to emit and listen to messages throughout the code. The upper case "Socket" is a type that had to import and reference due to this file being in TypeScript in order to specify the "type" of object corresponding to lower case "socket". They are being used at the very beginning of this script:

`io.on("connection", (socket: Socket) => {
  console.log('we should have a connection');

  socket.on("addUser", (userId) => {
    onlineUsers.set(userId, socket.id);
    socket.emit("getUsers", Array.from(onlineUsers));
  });
  
  socket.on("sendMessage", (data) => {
    const sendUserSocket = onlineUsers.get(data.to);
    if (sendUserSocket) {
      socket.to(sendUserSocket).emit("getMessage", data);
    }
  });

  socket.on("disconnect", () => {
    // Remove the disconnected socket from onlineUsers map
    for (const [userId, socketId] of onlineUsers) {
      console.log('this is getting activated')
      if (socketId === socket.id) {
        console.log(`deleting data from socket ${socketId}`)
        onlineUsers.delete(userId);
        break;
      }
    }
    console.log(`Socket disconnected: ${socket.id}`);
    console.log(`Updated onlineUsers: ${JSON.stringify(Array.from(onlineUsers))}`);
  })
});`

2023-06-09 02:20 UTC, jaheemprevost approved these changes

2023-06-09 15:51 UTC, royemosby approved these changes
GTG!

2023-06-09 15:52 UTC, merged